name: publish

on:
  push:
    tags:
      - '*'

jobs:
  publish-calypso-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the calypso Docker image
      run: |
        docker build . -t ghcr.io/workfoxes/calypso:latest -t ghcr.io/workfoxes/calypso:${GITHUB_REF#refs/*/} 
        docker run ghcr.io/workfoxes/calypso:latest
        docker push ghcr.io/workfoxes/calypso:${GITHUB_REF#refs/*/}
        docker push ghcr.io/workfoxes/calypso:$latest